### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by hardik-dadhich** [codingforentrepreneurs/Reactify-Django#6]
Kindly look for that...
****
cat /Users/hardikdadhich/.npm/_logs/2019-07-31T19_21_41_511Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose npm-session 449ead230de5209b
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall reactify-ui@0.1.0
7 info lifecycle reactify-ui@0.1.0~preinstall: reactify-ui@0.1.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 9ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 599ms
16 silly install loadAllDepsIntoIdealTree
17 silly fetchPackageMetaData error for react-scripts@2.0.0 request to http://visustar.francelab.fr.ibm.com:8081/nexus/content/repositories/mobile-npm/react-scripts failed, reason: getaddrinfo ENOTFOUND visustar.francelab.fr.ibm.com visustar.francelab.fr.ibm.com:8081
18 silly fetchPackageMetaData error for copyfiles@^2.0.0 request to http://visustar.francelab.fr.ibm.com:8081/nexus/content/repositories/mobile-npm/copyfiles failed, reason: getaddrinfo ENOTFOUND visustar.francelab.fr.ibm.com visustar.francelab.fr.ibm.com:8081
19 silly fetchPackageMetaData error for renamer@^0.7.0 request to http://visustar.francelab.fr.ibm.com:8081/nexus/content/repositories/mobile-npm/renamer failed, reason: getaddrinfo ENOTFOUND visustar.francelab.fr.ibm.com visustar.francelab.fr.ibm.com:8081
20 silly fetchPackageMetaData error for copyfiles@^2.0.0 request to http://visustar.francelab.fr.ibm.com:8081/nexus/content/repositories/mobile-npm/copyfiles failed, reason: getaddrinfo ENOTFOUND visustar.francelab.fr.ibm.com visustar.francelab.fr.ibm.com:8081
21 silly fetchPackageMetaData error for react-scripts@2.0.0 request to http://visustar.francelab.fr.ibm.com:8081/nexus/content/repositories/mobile-npm/react-scripts failed, reason: getaddrinfo ENOTFOUND visustar.francelab.fr.ibm.com visustar.francelab.fr.ibm.com:8081
22 silly fetchPackageMetaData error for renamer@^0.7.0 request to http://visustar.francelab.fr.ibm.com:8081/nexus/content/repositories/mobile-npm/renamer failed, reason: getaddrinfo ENOTFOUND visustar.francelab.fr.ibm.com visustar.francelab.fr.ibm.com:8081
23 timing stage:rollbackFailedOptional Completed in 0ms
24 timing stage:runTopLevelLifecycles Completed in 727ms
25 silly saveTree reactify-ui@0.1.0
25 silly saveTree ├─┬ react-dom@16.4.0
25 silly saveTree │ ├─┬ fbjs@0.8.16
25 silly saveTree │ │ ├── core-js@1.2.7
25 silly saveTree │ │ ├─┬ isomorphic-fetch@2.2.1
25 silly saveTree │ │ │ ├─┬ node-fetch@1.7.3
25 silly saveTree │ │ │ │ ├─┬ encoding@0.1.12
25 silly saveTree │ │ │ │ │ └─┬ iconv-lite@0.4.23
25 silly saveTree │ │ │ │ │   └── safer-buffer@2.1.2
25 silly saveTree │ │ │ │ └── is-stream@1.1.0
25 silly saveTree │ │ │ └── whatwg-fetch@2.0.4
25 silly saveTree │ │ ├─┬ loose-envify@1.3.1
25 silly saveTree │ │ │ └── js-tokens@3.0.2
25 silly saveTree │ │ ├── object-assign@4.1.1
25 silly saveTree │ │ ├─┬ promise@7.3.1
25 silly saveTree │ │ │ └── asap@2.0.6
25 silly saveTree │ │ ├── setimmediate@1.0.5
25 silly saveTree │ │ └── ua-parser-js@0.7.18
25 silly saveTree │ ├── loose-envify@1.3.1
25 silly saveTree │ ├── object-assign@4.1.1
25 silly saveTree │ └── prop-types@15.6.1
25 silly saveTree └── react@16.4.0
26 verbose type system
27 verbose stack FetchError: request to http://visustar.francelab.fr.ibm.com:8081/nexus/content/repositories/mobile-npm/copyfiles failed, reason: getaddrinfo ENOTFOUND visustar.francelab.fr.ibm.com visustar.francelab.fr.ibm.com:8081
27 verbose stack     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
27 verbose stack     at ClientRequest.emit (events.js:198:13)
27 verbose stack     at Socket.socketErrorListener (_http_client.js:392:9)
27 verbose stack     at Socket.emit (events.js:198:13)
27 verbose stack     at emitErrorNT (internal/streams/destroy.js:91:8)
27 verbose stack     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
27 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
28 verbose cwd /Users/hardikdadhich/Desktop/Couple-dial/acqnt-master/working-folder/src/reactify-ui
29 verbose Darwin 18.7.0
30 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
31 verbose node v10.16.0
32 verbose npm  v6.9.0
33 error code ENOTFOUND
34 error errno ENOTFOUND
35 error network request to http://visustar.francelab.fr.ibm.com:8081/nexus/content/repositories/mobile-npm/copyfiles failed, reason: getaddrinfo ENOTFOUND visustar.francelab.fr.ibm.com visustar.francelab.fr.ibm.com:8081
36 error network This is a problem related to network connectivity.
36 error network In most cases you are behind a proxy or have bad network settings.
36 error network
36 error network If you are behind a proxy, please make sure that the
36 error network 'proxy' config is set properly.  See: 'npm help config'
37 verbose exit [ 1, true ]
****

its giving me [this](url
![image](https://user-images.githubusercontent.com/25060629/62241657-350f4d00-b3f7-11e9-9dc1-2cd4450be094.png)
) error..

Is the issue related to version ? my package.json file same as this repo
I am using Mac OSX(x64)

**Comment by YlmRdm** [comment]
Try to uninstall create-react-app like this: 
`npm uninstall -g create-react-app`
